### ISSUE TITLE
应用配置后3dmigoto内的mods文件夹里的mod会被清除

### ISSUE THREAD

**Issue by Bitcolumn** [XiaoLinXiaoZhu/Mods-Manager-for-3Dmigoto#1]
如题， 在没有选中mod的情况下点击应用配置mods文件夹里原有的mod会被清除

**Comment by XiaoLinXiaoZhu** [comment]
这就是它怎么允许的：我并不了解3dmigoto的工作原理。所以说我采用了直接移动文件的方式来实现对于mod的动态管理
