### ISSUE TITLE
Can't use

### ISSUE THREAD

**Issue by s4-Liuzhuang** [XiaoLinXiaoZhu/Mods-Manager-for-3Dmigoto#14]
**Describe the bug**
![Screenshot 2024-10-18 231842](https://github.com/user-attachments/assets/965e588d-7b9e-4716-8c14-13ad512f8076)

**To Reproduce**
Open ZZZModManager 1.9.10

**Expected behavior**
Mods should show

**Screenshots**

**Laptop (please complete the following information):**
 - OS: Windows 11

**Comment by XiaoLinXiaoZhu** [comment]
收到了，这个bug是由于在初始化变量之前使用了变量，这很容易修复，我会尽快修复它。
