### ISSUE TITLE
1.9.10和1.9.9打开是初始状态不能使用

### ISSUE THREAD

**Issue by ChenchiIS** [XiaoLinXiaoZhu/Mods-Manager-for-3Dmigoto#15]
![屏幕截图 2024-10-19 165104](https://github.com/user-attachments/assets/a63c33d7-8738-4421-a4a2-e226a29554ea)

**Comment by XiaoLinXiaoZhu** [comment]
收到了，这个bug是由于在初始化变量之前使用了变量，这很容易修复，我会尽快修复它。
