### ISSUE TITLE
Drag through filters

### ISSUE THREAD

**Issue by Nerf1187** [XiaoLinXiaoZhu/Mods-Manager-for-3Dmigoto#16]
I think a good addition to the UI would be to allow the user to scroll through the filters, as they currently can go off the screen and become unclickable (shown by the image). I think just a scroll bar or something would be convenient to have.
![{017542E8-B94D-412D-916F-78984DFABB23}](https://github.com/user-attachments/assets/3db635fa-c468-4202-958e-b80dca475ee5)

**Comment by XiaoLinXiaoZhu** [comment]
This feature is already available. Use your mouse wheel to scroll on it to make it roll left and right.

Maybe I'll add a drag-and-drop feature in a later version, because it's more intuitive

**Comment by XiaoLinXiaoZhu** [comment]
in the new tool XXMM, this function has been realized

[XXMM](https://github.com/XiaoLinXiaoZhu/XX-Mod-Manager)
