### ISSUE TITLE
Need a feature to remove mods。需要一个删除mod的功能

### ISSUE THREAD

**Issue by pansuto** [XiaoLinXiaoZhu/Mods-Manager-for-3Dmigoto#18]
This manager is good, but it lacks a feature to remove mods. 这个管理器不错，但是缺少一个删除mod的功能。

**Comment by XiaoLinXiaoZhu** [comment]
You can click the mod and then click the "Open Mod Folder", than , you can delete.your mod.

Actually, this feature itself is easy to add, but what really bothers me is where to put the buttons and how to make them look beautiful......
