### ISSUE TITLE
增加拖動功能

### ISSUE THREAD

**Issue by pkkopkko000** [XiaoLinXiaoZhu/Mods-Manager-for-3Dmigoto#19]
一個實用的點子:如果可以多選模組拖動到分組,從而實現快速分類,那將大大增加分類速度,降低使用工具的時間成本

**Comment by XiaoLinXiaoZhu** [comment]
在新的工具 xxmm 中，你可以在导入mod的时候通过切换到指定的角色筛选页面实现角色分配。

xxmm：[XXMM](https://github.com/XiaoLinXiaoZhu/XX-Mod-Manager)
