### ISSUE TITLE
一点鄙见

### ISSUE THREAD

**Issue by ikaoda** [XiaoLinXiaoZhu/Mods-Manager-for-3Dmigoto#4]
大多是UI以及UI交互方面的：
**1**.感叹号建议去掉，详细页改为在主界面左键或者右键点击目标mod弹出
理由：
  a.感叹号不够直观；
  b.看详细页面需要多点一下，不够简便。
**2**.删除no description，默认留白或者只在编辑页面显示。
**3**.左边菜单栏：
  a."预设"改为"配置"或者”组“；
  b.将"编辑预设"以及主界面右下角"应用配置"移动到”配置“界面的二级界面(相当于默认需要创建一个预设)；
  c.删除预设时增加一个确认/取消的二级菜单。
**4**.添加框选/全选/反选功能(如果可以实现的话)，逐个点选不够便捷，mod只会日益增多。
**5**.优化角色标签排序(符号数字英文拼音首字母这个顺序一般比较常用吧)。
**6**.在设置里添加制作人信息(包括github地址)。

暂时想到这些，望大佬酌情参考。

**Comment by XiaoLinXiaoZhu** [comment]
> 大多是UI以及UI交互方面的： **1**.感叹号建议去掉，详细页改为在主界面左键或者右键点击目标mod弹出 理由： a.感叹号不够直观； b.看详细页面需要多点一下，不够简便。 **2**.删除no description，默认留白或者只在编辑页面显示。 **3**.左边菜单栏： a."预设"改为"配置"或者”组“； b.将"编辑预设"以及主界面右下角"应用配置"移动到”配置“界面的二级界面(相当于默认需要创建一个预设)； c.删除预设时增加一个确认/取消的二级菜单。 **4**.添加框选/全选/反选功能(如果可以实现的话)，逐个点选不够便捷，mod只会日益增多。 **5**.优化角色标签排序(符号数字英文拼音首字母这个顺序一般比较常用吧)。 **6**.在设置里添加制作人信息(包括github地址)。
> 
> 暂时想到这些，望大佬酌情参考。

我一条条的回复你吧：
1. 感叹号建议去掉，详细页改为在主界面左键或者右键点击目标mod弹出：
- 首先那个不是感叹号，那个是info的首字母的图标，在任何地方它都是查看详情或者查看信息的意思。
- 你要搞清楚详情页面的功能，那个地方主要是让用户能够编辑或者打开mod文件夹，展示信息实际上已经在卡片中详细的展示了。正常的使用情况是，你导入mod，然后它被归类进unknown，然后你再点进unknown分类里面通过那个界面编辑你的mod信息，之后你就不需要那个页面并且可以将其折叠起来了。
2. 删除no description，默认留白或者只在编辑页面显示。
- 没有必要的改变，no description 是为了让用户自己编辑描述
3. 左边菜单栏：
- 预设就是预设，不论是配置还是组都不是直观的名字
- 你似乎没有考虑排版的问题，而且可以不选择预设进行应用可以便捷的对于临时的mod搭配进行尝试，而不会自动保存在预设中。
4. 框选，全选，反选：
- 这让我怀疑你到底有没有用过mod，如果你用过的话，你应该知道，一个角色不能够应用多个mod。所以说无论是框选还是全选还是反选都是不明智的做法，最好最方便的办法就是点进你每个角色的分类里面，然后分别为它们单独选择mod。
5. 角色标签排序：
- 我正在考虑添加这个功能，如何进行合理的ui设计以及排布让我有点头疼
6. 制作人信息：
- 我之前想过添加，但是这会让设置界面的排版变得很奇怪。这并不是高优先级的事项，我会在解决我当前遇到的问题之后解决它。

我现在正在尝试当点击apply后自动切换到zzz并且自动按下F10来刷新，在1.8.1能够初步预览它的效果，但是这仍然存在一些问题。

**Comment by ikaoda** [comment]
> > 大多是UI以及UI交互方面的： **1**.感叹号建议去掉，详细页改为在主界面左键或者右键点击目标mod弹出 理由： a.感叹号不够直观； b.看详细页面需要多点一下，不够简便。 **2**.删除no description，默认留白或者只在编辑页面显示。 **3**.左边菜单栏： a." 预设"改为"配置"或者”组“； b.将"编辑预设"以及主界面右下角"应用配置"移动到”配置“界面的二级界面(相当于默认需要创建一个预设)； c.删除预设时增加一个确认/取消的二级菜单。 **4**.添加框选/全选/反选功能(如果可以实现的话)，逐个点选不够便捷，mod只会日益增多。 **5**.优化角色标签排序(符号数字英文拼音首字母这个顺序一般比较常用吧)。 **6**.在设置里添加制作人信息(包括github地址)。
> > 暂时想到这些，望大佬酌情参考。
> 
> 我一条条的回复你吧：
> 
> 1. 感叹号建议去掉，详细页改为在主界面左键或者右键点击目标mod弹出：
> 
> * 首先那个不是感叹号，那个是info的首字母的图标，在任何地方它都是查看详情或者查看信息的意思。
> * 你要搞清楚详情页面的功能，那个地方主要是让用户能够编辑或者打开mod文件夹，展示信息实际上已经在卡片中详细的展示了。 正常的使用情况是，你导入mod，然后它被归类进unknown，然后你再点进unknown分类里面通过那个界面编辑你的mod信息，之后你就不需要那个页面并且可以将其折叠起来了。
> 
> 2. 删除no description，默认留白或者只在编辑页面显示。
> 
> * 没有必要的改变，no description 是为了让用户自己编辑描述
> 
> 3. 左边菜单栏：
> 
> * 预设就是预设，不论是配置还是组都不是直观的名字
> * 你似乎没有考虑排版的问题，而且可以不选择预设进行应用可以便捷的对于临时的mod搭配进行尝试，而不会自动保存在预设中。
> 
> 4. 框选，全选，反选：
> 
> * 这让我怀疑你到底有没有用过mod，如果你用过的话，你应该知道，一个角色不能够应用多个mod。 所以说无论是框选还是全选还是反选都是不明智的做法，最好最方便的办法就是点进你每个角色的分类里面，然后分别为它们单独选择mod。
> 
> 5. 角色标签排序：
> 
> * 我正在考虑添加这个功能，如何进行合理的ui设计以及排布让我有点头疼
> 
> 6. 制作人信息：
> 
> * 我之前想过添加，但是这会让设置界面的排版变得很奇怪。 这并不是高优先级的事项，我会在解决我当前遇到的问题之后解决它。
> 
> 我现在正在尝试当点击apply后自动切换到zzz并且自动按下F10来刷新，在1.8.1能够初步预览它的效果，但是这仍然存在一些问题。


大佬辛苦了
