### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Chi-i-ka** [XiaoLinXiaoZhu/Mods-Manager-for-3Dmigoto#8]
非常喜欢最近更新的UI，和绝区零的风格很匹配
但使用上感觉缺乏的一些功能，不知道大佬是否有准备加入这些功能，反馈一下

1. 开启加载器和开启游戏的按钮
2. 合并mod的keyswap信息和快捷更高（右侧页面下半部有空位感觉适合加入这个功能）
3. 左侧页面新加的UI的贴图有些黑块感觉有点影响美观
![20241012124328](https://github.com/user-attachments/assets/4ff0c678-f6a4-4472-b104-f0c438ba9891)
4. 没有切换的mod截图一般只有一人多为长方形，图片预览的自适应对于这类显示效果不太好，能加入自己调整的功能会方便些
5. 预览的标题字体大小比较大，对于一些稍微长一些的备注显示不全，感觉可以加入自行调节字体大小

**Comment by XiaoLinXiaoZhu** [comment]
很有价值的建议，让我一个个来回答：
## 1. 开启加载器和开启游戏的按钮：
- 实际上这个功能并不难做，但是3dmigoto和绝区零都需要以管理员身份启动，这导致这件事情可能没有预期中的那么方便，我自己是写了个bat点击就会将它们一起启动hmmm。后续应该会加入这个功能。
- 而且目前ZZZModManager还存在一些问题，比如说在管理员模式下拖拽图片设置封面的功能会失效（我暂时不知道这是为什么）
- 随着越来越多功能的加入，整个程序变得越来越臃肿（比如说要实现你说的这个功能，我就需要在设置里面多加一条绝区零游戏的链接的输入框，以及多两个打开zzzmi和zzz的按钮，我现在已经对于这些ui排布够头疼的了QAQ），这使得维护的难度越来越高，这有点偏离我自己的预期。这段时间可能主要是聚焦于 完善指南 和 实现能够在点击apply之后自动唤起绝区零并且刷新mod的功能，我认为这两点可能更加重要一点。

## 2. 合并mod的keyswap信息和快捷更高（右侧页面下半部有空位感觉适合加入这个功能）：
- 实际上，描述就是为了让你能够记录这些信息的，你完全可以将keyswap写进描述里面，并且记录它们这些按钮分别是什么功能。在未来的版本，ZZZModManger或许会支持自动读取mod中的ini文件来获取keyswap信息，并将其展示出来，但是它仍然无法确认这些信息对应哪些功能，尤其是对于一并使用了RabbitFX还有一些高级的快捷键（比如说 按住某个键生效 或者 长按某个键可以调整亮度）。
- 所以说就目前来看，手动补充描述信息仍然是比较便捷通用的方式。

## 3. 左侧页面新加的UI的贴图有些黑块感觉有点影响美观：
- 这个黑块是我故意添加的，是为了使得整个视觉更加的平衡。你觉得奇怪，可能是因为preset页面的背景还没有调整——它应该更暗一点，让按钮和标题突出，并且与那个黑块照应。

## 4. 没有切换的mod截图一般只有一人多为长方形，图片预览的自适应对于这类显示效果不太好，能加入自己调整的功能会方便些：
- 如果加入能够自动调整的功能就意味着我需要加入一个图片编辑和记录功能，但是实际上图片编辑本来就有很多很好用的工具。对于单个角色，实际上你可以将游戏中的拍照作为你的mod封面，这对你来说不仅更为美观，而且还具有个人特色。
- 拍照的路径默认在miHoYo Launcher\games\ZenlessZoneZero Game\ScreenShot，当你完成拍照后，你可以将文件夹中的文件直接拖拽到mod卡片上，将其设置为mod卡片的封面。

## 5. 预览的标题字体大小比较大，对于一些稍微长一些的备注显示不全，感觉可以加入自行调节字体大小
- 实际上，我的电脑是2k的分辨率，我根据最佳的视觉体验将其调整为了105 ppi，这对于大部分情况下属于较小的ppi，但是在别人的电脑上可能会显得较大。
- 一般来说，在较小的屏幕上推荐全屏显示，这样的话，能够较好的展示信息。实际上按下ctrl + shitf + _ 就能够将缩放比缩小，但是目前因为记忆窗口位置的功能，导致调整缩放比之后，窗口的位置和大小可能不正确，此问题会在后面慢慢修复。
- 预览的标题过长，实际上这应该是你的mod的管理的问题，你的mod的名称应该足够简洁明了而更多的信息则应该在mod的备注里面展示。
